---
- hosts: 127.0.0.1
  connection: local
  vars:
    input: "{{ lookup('file','../package.json') | from_json }}"
  # vars_files:
  #   - ../configuration.yaml
  tasks:
    - name: Create interfaces Dictionary
      set_fact:
        package_json: "{{ input }}"
    - name: See if it worked
      debug:
        var: package_json.name
    # - name: Build the service
    #   ansible.builtin.shell: |
    #     yarn
    #     yarn build
    #     yarn bundle
    - name: Create directory for remote service files
      ansible.builtin.file:
        path: tmp
        state: directory
    - name: Generate remote service files
      template:
        src: "{{ item.src }}"
        dest: "tmp/{{ item.dest }}"
        mode: "u=rw,o=r,g=r"
        owner: root
        group: root
      loop:
        - src: template.service.j2
          dest: template-filled.service.j2
    # - name: Prep root ssh
    #   file:
    #     path: "{{ local_workspace.mount_point }}/root/.ssh"
    #     state: directory
    #     recurse: yes
    #     mode: "u=rw,g=,o="
    # - name: Generate files
    #   template:
    #     src: "{{ item.src }}"
    #     dest: "{{ local_workspace.mount_point }}{{ item.dest }}"
    #     mode: "u=rw,o=r,g=r"
    #     owner: root
    #     group: root
    #   loop:
    #     - src: templates/etc/hostname.j2
    #       dest: /etc/hostname
    #     - src: templates/etc/hosts.j2
    #       dest: /etc/hosts
    #     - src: templates/etc/network/interfaces.j2
    #       dest: /etc/network/interfaces
    #     - src: templates/root/.ssh/authorized_keys.j2
    #       dest: /root/.ssh/authorized_keys
    # - name: Remove ssh access
    #   file:
    #     path: /root/.ssh/authorized_keys
    #     state: absent
    #   when: "{{ is_production_mode }}"